# wrangler.toml
# CloudFlare Workers configuration (used by EdgePages)

name = "cbthelper"
main = "api/llm-proxy-universal.js"
compatibility_date = "2024-01-01"

# 环境变量配置
# 这些值需要在 EdgePages 控制台中设置
# [vars]
# LLM_API_KEY = ""
# LLM_API_URL = ""
# LLM_MODEL_NAME = ""

# 路由配置
[routes]
patterns = ["/api/llm-proxy"]

# 构建配置
[build]
command = "npm run build"

# 静态资源配置
[site]
bucket = "./dist"

# Workers KV 配置（如果需要缓存）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"